name = "worker"
type = "javascript"
account_id = "1fed5897e8e8d7fa525091234a77b5e4"
workers_dev = true
route = ""
zone_id = ""
vars = {  DEBUG_MODE = "hello Thomas" } 

[build]
command = "npm i && npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"

[durable_objects]
bindings = [{name = "COUNTER", class_name = "Counter"},
  {name = "TEST", class_name = "Test"}
]
